import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.JFrame;

public class FriendsList extends javax.swing.JFrame {

    /**
     * Creates new form FriendsList
     */
    public FriendsList(Client client) {
        initComponents();
        this.client = client;
        friends = new ArrayList<Friend>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        AddButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        SelectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // DO IT HERE
        PopulateList();
        jScrollPane1.setViewportView(jList1);

        AddButton.setText("Add");
        AddButton.setToolTipText("");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		AddButtonActionPerformed(evt);
        	}
        });

        DeleteButton.setText("Delete");
        DeleteButton.setToolTipText("");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		DeleteButtonActionPerformed(evt);
        	}
        });

        ExitButton.setText("Exit");
        ExitButton.setToolTipText("");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        
        SelectButton.setText("Select");
        SelectButton.setToolTipText("");
        SelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 171, Short.MAX_VALUE)
                        .addComponent(AddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelectButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExitButton))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(DeleteButton)
                    .addComponent(SelectButton)
                    .addComponent(ExitButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed
    
    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	// need a couple of variables
    	String name;
    	
    	name = JOptionPane.showInputDialog(
                this,
                "Enter your friend's name:",
                "Screen name selection",
                JOptionPane.PLAIN_MESSAGE);
    	
    	client.SendMessage(new Message(name), "SEARCH");
    }
    
    public void PopulateList()
    {
    	final ArrayList<String> friendNames = new ArrayList<String>();
    	for (Friend x: friends)
    	{
    		friendNames.add(x.GetDisplay());
    	}
    	jList1.setModel(new javax.swing.AbstractListModel() {
            public int getSize() { return friendNames.size(); }
            public Object getElementAt(int i) { return friendNames.get(i); }
        });
    }
    
    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	friends.remove(jList1.getSelectedIndex());
    	PopulateList();
    }
    
    private void SelectButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	// SPAWN NEW CHATWINDOW!! Danger!
    	chat = new ChatWindow(client, this, friends.get(jList1.getSelectedIndex()).GetName());
    	chat.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    	chat.setTitle(friends.get(jList1.getSelectedIndex()).GetDisplay());
    	chat.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton SelectButton;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private static Client client;
    public ArrayList<Friend> friends = new ArrayList<Friend>();
    public ChatWindow chat;
    // End of variables declaration//GEN-END:variables
}
